kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway
data:
  application.yml: |-
    spring:
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: employee
              uri: lb://employee
              predicates:
                - Path=/employee/**
              filters:
                - RewritePath=/employee/(?<path>.*), /$\{path}
            - id: department
              uri: lb://department
              predicates:
                - Path=/department/**
              filters:
                - RewritePath=/department/(?<path>.*), /$\{path}
            - id: organization
              uri: lb://organization
              predicates:
                - Path=/organization/**
              filters:
                - RewritePath=/organization/(?<path>.*), /$\{path}
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: gateway
# data:
#   logging.pattern.console: "%d{HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#   spring.cloud.kubernetes.discovery.all-namespaces: "true"
#   zuul.routes.department.path: "/department/**"
#   zuul.routes.employee.path: "/employee/**"
#   zuul.routes.organization.path: "/organization/**"                